services:
  - type: web
    name: youtube-downloader
    runtime: python3
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: python api_server.py
    plan: free
buildCommand: |
  pip install --upgrade pip